"""
OpenIntent SDK - Python client for the OpenIntent Coordination Protocol.

A lightweight SDK for coordinating intent across humans and AI agents.
"""

from .client import AsyncOpenIntentClient, OpenIntentClient
from .exceptions import (
    ConflictError,
    LeaseConflictError,
    NotFoundError,
    OpenIntentError,
    ValidationError,
)
from .models import (
    AggregateStatus,
    ArbitrationRequest,
    CostSummary,
    CostType,
    Decision,
    EventType,
    Intent,
    IntentAttachment,
    IntentCost,
    IntentEvent,
    IntentFailure,
    IntentLease,
    IntentPortfolio,
    IntentState,
    IntentStatus,
    IntentSubscription,
    LeaseStatus,
    MembershipRole,
    PortfolioMembership,
    PortfolioStatus,
    RetryPolicy,
    RetryStrategy,
)
from .validation import (
    InputValidationError,
    validate_agent_id,
    validate_cost_record,
    validate_intent_create,
    validate_lease_acquire,
    validate_non_negative,
    validate_positive_int,
    validate_required,
    validate_scope,
    validate_string_length,
    validate_subscription,
    validate_url,
    validate_uuid,
)

__version__ = "0.1.0"
__all__ = [
    "OpenIntentClient",
    "AsyncOpenIntentClient",
    "Intent",
    "IntentState",
    "IntentStatus",
    "IntentEvent",
    "EventType",
    "IntentLease",
    "LeaseStatus",
    "ArbitrationRequest",
    "Decision",
    "IntentPortfolio",
    "PortfolioStatus",
    "PortfolioMembership",
    "MembershipRole",
    "AggregateStatus",
    "IntentAttachment",
    "IntentCost",
    "CostSummary",
    "CostType",
    "RetryPolicy",
    "RetryStrategy",
    "IntentFailure",
    "IntentSubscription",
    "OpenIntentError",
    "ConflictError",
    "NotFoundError",
    "LeaseConflictError",
    "ValidationError",
    "InputValidationError",
    "validate_required",
    "validate_string_length",
    "validate_positive_int",
    "validate_non_negative",
    "validate_uuid",
    "validate_url",
    "validate_scope",
    "validate_agent_id",
    "validate_intent_create",
    "validate_lease_acquire",
    "validate_cost_record",
    "validate_subscription",
]
