"""
OpenIntent SDK - Python client for the OpenIntent Coordination Protocol.

A lightweight SDK for coordinating intent across humans and AI agents.
"""

from typing import Any

from .agents import (
    Agent,
    AgentConfig,
    BaseAgent,
    Coordinator,
    GuardrailError,
    Identity,
    IntentSpec,
    PortfolioSpec,
    Worker,
    input_guardrail,
    on_access_requested,
    on_all_complete,
    on_approval_denied,
    on_approval_granted,
    on_assignment,
    on_complete,
    on_conflict,
    on_drain,
    on_escalation,
    on_event,
    on_governance_blocked,
    on_handoff,
    on_identity_registered,
    on_lease_available,
    on_message,
    on_quorum,
    on_retry,
    on_state_change,
    on_task,
    on_trigger,
    output_guardrail,
)
from .client import AsyncOpenIntentClient, OpenIntentClient
from .exceptions import (
    ConflictError,
    LeaseConflictError,
    NotFoundError,
    OpenIntentError,
    ValidationError,
)
from .llm import LLMConfig, LLMEngine, Tool, ToolDef, define_tool, tool
from .mcp import MCPTool, parse_mcp_uri
from .models import (
    AccessPolicy,
    AccessRequest,
    AccessRequestStatus,
    ACLEntry,
    AgentCapacity,
    # RFC-0018: Cryptographic Agent Identity
    AgentIdentity,
    # RFC-0016: Agent Lifecycle & Health
    AgentRecord,
    AgentStatus,
    AggregateStatus,
    ApprovalRequest,
    ApprovalStatus,
    ArbitrationRequest,
    # RFC-0019: Verifiable Event Logs
    ChainVerification,
    # RFC-0021: Agent-to-Agent Messaging
    Channel,
    ChannelMessage,
    ChannelOptions,
    ChannelStatus,
    Checkpoint,
    ConsistencyProof,
    # RFC-0013: Coordinator Governance
    CoordinatorLease,
    CoordinatorStatus,
    CoordinatorType,
    CostSummary,
    CostType,
    Credential,
    # RFC-0014: Credential Vaults & Tool Scoping
    CredentialVault,
    Decision,
    DecisionRecord,
    DecisionType,
    Escalation,
    EscalationPriority,
    EscalationStatus,
    EventProof,
    EventType,
    GrantConstraints,
    Guardrails,
    Heartbeat,
    HeartbeatConfig,
    IdentityChallenge,
    IdentityVerification,
    Intent,
    IntentACL,
    IntentAttachment,
    IntentContext,
    IntentCost,
    IntentEvent,
    IntentFailure,
    IntentLease,
    IntentPortfolio,
    IntentState,
    IntentStatus,
    IntentSubscription,
    IntentTemplate,
    LeaseStatus,
    LLMRequestPayload,
    LogCheckpoint,
    MemberPolicy,
    MembershipRole,
    # RFC-0015: Agent Memory
    MemoryEntry,
    MemoryPolicy,
    MemoryScope,
    MemoryType,
    MerkleProof,
    MerkleProofEntry,
    MessageStatus,
    MessageType,
    PeerInfo,
    Permission,
    Plan,
    PlanCondition,
    PlanState,
    PortfolioMembership,
    PortfolioStatus,
    RetryPolicy,
    RetryStrategy,
    StreamState,
    StreamStatus,
    # RFC-0012: Task Decomposition & Planning
    Task,
    TaskStatus,
    TimestampAnchor,
    ToolCallPayload,
    ToolGrant,
    ToolInvocation,
    ToolRequirement,
    # RFC-0020: Distributed Tracing
    TracingContext,
    # RFC-0017: Triggers & Reactive Scheduling
    Trigger,
    TriggerCondition,
    TriggerLineage,
    TriggerType,
)
from .streaming import (
    EventQueue,
    SSEEvent,
    SSEEventType,
    SSEStream,
    SSESubscription,
)
from .validation import (
    InputValidationError,
    validate_agent_id,
    validate_cost_record,
    validate_intent_create,
    validate_lease_acquire,
    validate_non_negative,
    validate_positive_int,
    validate_required,
    validate_scope,
    validate_string_length,
    validate_subscription,
    validate_url,
    validate_uuid,
)
from .workflow import AccessPolicy as WorkflowAccessPolicy  # noqa: F401
from .workflow import (
    AllowEntry,  # noqa: F401
    DelegateConfig,  # noqa: F401
    GovernanceConfig,
    IdentityConfig,
    PermissionLevel,  # noqa: F401
    PermissionsConfig,  # noqa: F401
    PhaseConfig,
    VerificationConfig,
    WorkflowError,
    WorkflowNotFoundError,
    WorkflowSpec,
    WorkflowValidationError,
    validate_workflow,
)


def get_server() -> tuple[Any, Any, Any]:
    """Lazy import for server components (requires server extras)."""
    try:
        from .server import OpenIntentServer, ServerConfig, create_app

        return OpenIntentServer, ServerConfig, create_app
    except ImportError:
        raise ImportError(
            "Server components require the 'server' extras. "
            "Install with: pip install openintent[server]"
        )


__version__ = "0.13.2"
__all__ = [
    "OpenIntentClient",
    "AsyncOpenIntentClient",
    "ACLEntry",
    "AccessPolicy",
    "AccessRequest",
    "AccessRequestStatus",
    "AgentIdentity",
    "AggregateStatus",
    "EventProof",
    "ChainVerification",
    "ConsistencyProof",
    "IdentityChallenge",
    "IdentityVerification",
    "LogCheckpoint",
    "MerkleProof",
    "MerkleProofEntry",
    "TimestampAnchor",
    "Intent",
    "IntentState",
    "IntentStatus",
    "IntentEvent",
    "EventType",
    "IntentLease",
    "LeaseStatus",
    "IntentACL",
    "IntentContext",
    "ArbitrationRequest",
    "Decision",
    "IntentPortfolio",
    "PortfolioStatus",
    "PortfolioMembership",
    "MembershipRole",
    "IntentAttachment",
    "IntentCost",
    "CostSummary",
    "CostType",
    "PeerInfo",
    "Permission",
    "RetryPolicy",
    "RetryStrategy",
    "IntentFailure",
    "IntentSubscription",
    "ToolCallPayload",
    "LLMRequestPayload",
    "StreamState",
    "StreamStatus",
    "Task",
    "TaskStatus",
    "Plan",
    "PlanState",
    "Checkpoint",
    "PlanCondition",
    "MemoryPolicy",
    "ToolRequirement",
    "CoordinatorLease",
    "CoordinatorType",
    "CoordinatorStatus",
    "Guardrails",
    "DecisionRecord",
    "DecisionType",
    "Escalation",
    "EscalationStatus",
    "EscalationPriority",
    "ApprovalRequest",
    "ApprovalStatus",
    "CredentialVault",
    "Credential",
    "ToolGrant",
    "ToolInvocation",
    "GrantConstraints",
    "MemoryEntry",
    "MemoryType",
    "MemoryScope",
    "AgentRecord",
    "AgentStatus",
    "Heartbeat",
    "AgentCapacity",
    "HeartbeatConfig",
    "Trigger",
    "TriggerType",
    "TriggerCondition",
    "IntentTemplate",
    "TriggerLineage",
    "TracingContext",
    "Channel",
    "ChannelMessage",
    "ChannelOptions",
    "ChannelStatus",
    "MemberPolicy",
    "MessageStatus",
    "MessageType",
    "OpenIntentError",
    "ConflictError",
    "NotFoundError",
    "LeaseConflictError",
    "ValidationError",
    "InputValidationError",
    "validate_required",
    "validate_string_length",
    "validate_positive_int",
    "validate_non_negative",
    "validate_uuid",
    "validate_url",
    "validate_scope",
    "validate_agent_id",
    "validate_intent_create",
    "validate_lease_acquire",
    "validate_cost_record",
    "validate_subscription",
    "SSEEvent",
    "SSEEventType",
    "SSEStream",
    "SSESubscription",
    "EventQueue",
    "Agent",
    "BaseAgent",
    "Coordinator",
    "Worker",
    "AgentConfig",
    "Identity",
    "IntentSpec",
    "PortfolioSpec",
    "GuardrailError",
    "input_guardrail",
    "on_access_requested",
    "on_all_complete",
    "on_approval_denied",
    "on_approval_granted",
    "on_assignment",
    "on_complete",
    "on_conflict",
    "on_drain",
    "on_escalation",
    "on_event",
    "on_governance_blocked",
    "on_handoff",
    "on_identity_registered",
    "on_lease_available",
    "on_message",
    "on_quorum",
    "on_retry",
    "on_state_change",
    "on_task",
    "on_trigger",
    "output_guardrail",
    "WorkflowSpec",
    "WorkflowError",
    "WorkflowValidationError",
    "WorkflowNotFoundError",
    "IdentityConfig",
    "VerificationConfig",
    "PhaseConfig",
    "GovernanceConfig",
    "validate_workflow",
    "get_server",
    "LLMConfig",
    "LLMEngine",
    "ToolDef",
    "define_tool",
    "Tool",
    "tool",
    "MCPTool",
    "parse_mcp_uri",
]
