"""
OpenIntent SDK - Python client for the OpenIntent Coordination Protocol.

A lightweight SDK for coordinating intent across humans and AI agents.
"""

from typing import Any

from .agents import (
    Agent,
    AgentConfig,
    BaseAgent,
    Coordinator,
    IntentSpec,
    PortfolioSpec,
    Worker,
    on_access_requested,
    on_all_complete,
    on_assignment,
    on_complete,
    on_conflict,
    on_drain,
    on_escalation,
    on_event,
    on_lease_available,
    on_quorum,
    on_state_change,
    on_task,
    on_trigger,
)
from .client import AsyncOpenIntentClient, OpenIntentClient
from .exceptions import (
    ConflictError,
    LeaseConflictError,
    NotFoundError,
    OpenIntentError,
    ValidationError,
)
from .models import (
    ACLEntry,
    AccessPolicy,
    AccessRequest,
    AccessRequestStatus,
    AggregateStatus,
    ArbitrationRequest,
    CostSummary,
    CostType,
    Decision,
    EventType,
    Intent,
    IntentACL,
    IntentAttachment,
    IntentContext,
    IntentCost,
    IntentEvent,
    IntentFailure,
    IntentLease,
    IntentPortfolio,
    IntentState,
    IntentStatus,
    IntentSubscription,
    LeaseStatus,
    LLMRequestPayload,
    MembershipRole,
    PeerInfo,
    Permission,
    PortfolioMembership,
    PortfolioStatus,
    RetryPolicy,
    RetryStrategy,
    StreamState,
    StreamStatus,
    ToolCallPayload,
    # RFC-0012: Task Decomposition & Planning
    Task,
    TaskStatus,
    Plan,
    PlanState,
    Checkpoint,
    PlanCondition,
    MemoryPolicy,
    ToolRequirement,
    # RFC-0013: Coordinator Governance
    CoordinatorLease,
    CoordinatorType,
    CoordinatorStatus,
    Guardrails,
    DecisionRecord,
    DecisionType,
    # RFC-0014: Credential Vaults & Tool Scoping
    CredentialVault,
    Credential,
    ToolGrant,
    ToolInvocation,
    GrantConstraints,
    # RFC-0015: Agent Memory
    MemoryEntry,
    MemoryType,
    MemoryScope,
    # RFC-0016: Agent Lifecycle & Health
    AgentRecord,
    AgentStatus,
    Heartbeat,
    AgentCapacity,
    HeartbeatConfig,
    # RFC-0017: Triggers & Reactive Scheduling
    Trigger,
    TriggerType,
    TriggerCondition,
    IntentTemplate,
    TriggerLineage,
)
from .streaming import (
    EventQueue,
    SSEEvent,
    SSEEventType,
    SSEStream,
    SSESubscription,
)
from .validation import (
    InputValidationError,
    validate_agent_id,
    validate_cost_record,
    validate_intent_create,
    validate_lease_acquire,
    validate_non_negative,
    validate_positive_int,
    validate_required,
    validate_scope,
    validate_string_length,
    validate_subscription,
    validate_url,
    validate_uuid,
)
from .workflow import (
    AllowEntry,  # noqa: F401
    DelegateConfig,  # noqa: F401
    GovernanceConfig,
    PermissionLevel,  # noqa: F401
    PermissionsConfig,  # noqa: F401
    PhaseConfig,
    WorkflowError,
    WorkflowNotFoundError,
    WorkflowSpec,
    WorkflowValidationError,
    validate_workflow,
)
from .workflow import AccessPolicy as WorkflowAccessPolicy  # noqa: F401


def get_server() -> tuple[Any, Any, Any]:
    """Lazy import for server components (requires server extras)."""
    try:
        from .server import OpenIntentServer, ServerConfig, create_app

        return OpenIntentServer, ServerConfig, create_app
    except ImportError:
        raise ImportError(
            "Server components require the 'server' extras. "
            "Install with: pip install openintent[server]"
        )


__version__ = "0.8.0"
__all__ = [
    "OpenIntentClient",
    "AsyncOpenIntentClient",
    "ACLEntry",
    "AccessPolicy",
    "AccessRequest",
    "AccessRequestStatus",
    "AggregateStatus",
    "Intent",
    "IntentState",
    "IntentStatus",
    "IntentEvent",
    "EventType",
    "IntentLease",
    "LeaseStatus",
    "IntentACL",
    "IntentContext",
    "ArbitrationRequest",
    "Decision",
    "IntentPortfolio",
    "PortfolioStatus",
    "PortfolioMembership",
    "MembershipRole",
    "IntentAttachment",
    "IntentCost",
    "CostSummary",
    "CostType",
    "PeerInfo",
    "Permission",
    "RetryPolicy",
    "RetryStrategy",
    "IntentFailure",
    "IntentSubscription",
    "ToolCallPayload",
    "LLMRequestPayload",
    "StreamState",
    "StreamStatus",
    "Task",
    "TaskStatus",
    "Plan",
    "PlanState",
    "Checkpoint",
    "PlanCondition",
    "MemoryPolicy",
    "ToolRequirement",
    "CoordinatorLease",
    "CoordinatorType",
    "CoordinatorStatus",
    "Guardrails",
    "DecisionRecord",
    "DecisionType",
    "CredentialVault",
    "Credential",
    "ToolGrant",
    "ToolInvocation",
    "GrantConstraints",
    "MemoryEntry",
    "MemoryType",
    "MemoryScope",
    "AgentRecord",
    "AgentStatus",
    "Heartbeat",
    "AgentCapacity",
    "HeartbeatConfig",
    "Trigger",
    "TriggerType",
    "TriggerCondition",
    "IntentTemplate",
    "TriggerLineage",
    "OpenIntentError",
    "ConflictError",
    "NotFoundError",
    "LeaseConflictError",
    "ValidationError",
    "InputValidationError",
    "validate_required",
    "validate_string_length",
    "validate_positive_int",
    "validate_non_negative",
    "validate_uuid",
    "validate_url",
    "validate_scope",
    "validate_agent_id",
    "validate_intent_create",
    "validate_lease_acquire",
    "validate_cost_record",
    "validate_subscription",
    "SSEEvent",
    "SSEEventType",
    "SSEStream",
    "SSESubscription",
    "EventQueue",
    "Agent",
    "BaseAgent",
    "Coordinator",
    "Worker",
    "AgentConfig",
    "IntentSpec",
    "PortfolioSpec",
    "on_access_requested",
    "on_all_complete",
    "on_assignment",
    "on_complete",
    "on_conflict",
    "on_drain",
    "on_escalation",
    "on_event",
    "on_lease_available",
    "on_quorum",
    "on_state_change",
    "on_task",
    "on_trigger",
    "WorkflowSpec",
    "WorkflowError",
    "WorkflowValidationError",
    "WorkflowNotFoundError",
    "PhaseConfig",
    "GovernanceConfig",
    "validate_workflow",
    "get_server",
]
